language: go
go:
  - "1.x"
install:
  - go get github.com/onsi/ginkgo/ginkgo github.com/golang/dep/cmd/dep
  - go install github.com/onsi/ginkgo/ginkgo github.com/golang/dep/cmd/dep
  - make install
script: make test